# Generated by Django 2.2 on 2020-07-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='total_amount',
        ),
    ]
